# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Continuous Integrations With Git Actions

on:
  push:
    branches: [codando_na_secao_17]
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build Application Jar
      working-directory: ./Projeto/rest-with-springboot-and-java-erudio
      run: mvn clean package
    
    - name: Docker Compose Build
      working-directory: ./Projeto
      run: docker compose build

    - name: Publish to Docker Hub Container Registry
      run: 
        docker tag ${{ secrets.DOCKER_USERNAME }}/spring-app:latest ${{ secrets.DOCKER.USERNAME }}/spring-app:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
